
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'webzaim' do
  config = use_native_modules!
  use_frameworks!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  pod 'YandexMobileMetrica/Dynamic', '4.4.0'

  target 'webzaimTests' do
    inherit! :complete
    use_frameworks!
    # Pods for testing
  end

 # Для корректной работы библиотеки просмотра RNPDF
  pre_install do |installer|
      installer.pod_targets.each do |pod|
        if pod.name.eql?('RNPDF')
          def pod.build_type
            Pod::BuildType.static_library
          end
        end
      end
    end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
    end
  end
end
