export enum ROUTES {
    // common
    ONBOARDING = 'OnboardingScreen',
    CALCULATOR = 'CalculatorScreen',
    UPDATE_APP = 'UpdateAppScreen',
    UNDER_CONSTRUCTION = 'UnderConstructionScreen',
    DOCUMENT = 'DocumentScreen',
    PAYMENT = 'PaymentScreen',
    ARTICLE = 'ArticleScreen',
    SMS_CONFIRMATION = 'SmsConfirmationScreen',
    ERROR = 'ErrorScreen',
    ERROR_500 = 'Error500Screen',
    LOG = 'Log',
    // main tabs
    MAIN = 'MainScreen',
    PROMOTIONS_STACK = 'PromotionsStack',
    HISTORY = 'HistoryScreen',
    LOANS_STACK = 'LoansScreen',
    PROFILE_STACK = 'ProfileScreen',
    OTHER_STACK = 'OtherStack',
    // auth
    LOGIN = 'LoginScreen',
    RECOVER_LOGIN = 'RecoverScreen',
    FAST_LOGIN = 'FastLoginScreen',
    WELCOME = 'WelcomeScreen',
    AUTH = 'AuthScreen',
    CHANGE_PASSWORD = 'ChangePasswordScreen',
    // registrations
    REGISTRATION_VARIANTS = 'RegistrationVariantsScreen',
    REGISTRATION_CONFIRMATION = 'RegistrationConfirmationScreen',
    REGISTRATION = 'RegistrationScreen',
    REGISTRATION_DOCUMENTS = 'RegistrationDocumentsScreen',
    REGISTRATION_PASSPORT = 'RegistrationPassportScreen',
    REGISTRATION_ADDRESS = 'RegistrationAddressScreen',
    REGISTRATION_ADDITIONAL_DATA = 'RegistrationAdditionalDataScreen',
    REGISTRATION_LOAN_REQUEST = 'RegistrationLoanRequestScreen',
    REGISTRATION_MONEY_TRANSFER = 'RegistrationMoneyTransferScreen',
    REGISTRATION_MONEY_TRANSFER_ADD = 'RegistrationMoneyTransferAddScreen',
    REGISTRATION_EXTERNAL = 'RegistrationExternalScreen',
    REGISTRATION_REQUEST_DOCUMENTS = 'RegistrationLoanDocumentsScreen',
    // loans
    USER_LOANS = 'UserLoansScreen',
    LOAN = 'LoanScreen',
    LOAN_INFO = 'LoanInfoScreen',
    LOAN_DOCUMENTS = 'LoanDocumentsScreen',
    LOAN_PROLONGATION = 'LoanProlongationScreen',
    LOAN_PROLONGATION_CONFIRM = 'LoanProlongationConfirmScreen',
    LOAN_PAYMENT_METHOD = 'LoanPaymentMethodScreen',
    LOAN_PAYMENT_SUM = 'LoanPaymentSumScreen',
    LOAN_REQUEST_MONEY_TRANSFER = 'LoanRequestMoneyTransfer',
    LOAN_REQUEST_MONEY_TRANSFER_ADD = 'LoanRequestMoneyTransferAdd',
    LOAN_REQUEST_DOCUMENTS = 'LoanRequestDocumnets',
    LOAN_REQUEST_ADD_CARD = 'LoanRequestAddCard',
    LOAN_REQUEST_ADD_BANK = 'LoanRequestAddBank',
    LOAN_REQUEST_CONFIRM = 'LoanRequestConfirm',
    LOAN_ADDON_DESCRIPTION = 'LoanAddonDescription',
    PASSPORT_SCAN = 'PassportScanScreen',
    // profile
    PROFILE_LIST = 'ProfileListScreen',
    USER_PROFILE = 'UserProfileScreen',
    USER_APPEALS = 'UserAppealsScreen',
    APPEAL_CREATE = 'AppealCreateScreen',
    APPEALS_CATEGORIES = 'AppealsCategoriesScreen',
    APPEALS_LIST = 'AppealsListScreen',
    USER_MONEY_TRANSFER = 'UserMoneyTransferScreen',
    USER_MONEY_TRANSFER_ADD = 'UserMoneyTransferAddScreen',
    USER_MONEY_TRANSFER_ADD_CARD = 'UserMoneyTransferAddCardScreen',
    USER_MONEY_TRANSFER_ADD_BANK = 'UserMoneyTransferAddBankScreen',
    APP_SETTINGS = 'AppSettingsScreen',
    // other
    OTHER = 'OtherScreen',
    ABOUT = 'AboutScreen',
    FAQ = 'FAQScreen',
    FAQ_ANSWER = 'FAQAnswerScreen',
    NEWS = 'NewsScreen',
    POST = 'PostScreen',
    APP_DOCUMENTS_LIST = 'AppDocumentsList',
    APP_DOCUMENT = 'AppDocument',
    // promotions
    PROMOTIONS = 'PromotionsScreen',
    PROMOTION = 'PromotionScreen'
}
